services:
    mysql:
        image: mysql:8.4
        restart: always
        container_name: mysql-nlw
        environment:
            - MYSQL_ROOT_PASSWORD=3c905btX_cruz
        
        networks:
        - nlw-network
networks:
  nlw-network:
    driver: bridge